### ISSUE TITLE
Add support for ant as external service

### ISSUE THREAD

**Issue by ezhulenev** [collectivemedia/celos#647]
In some of our workflows we are relying on ant. Currently we run it as java application from Oozie workflow. It would be much more convenient/cleaner if Celos itself would support launching ant scripts.

**Comment by manuel** [comment]
@ezhulenev Please post a link/example of such an Ant script.

**Comment by ezhulenev** [comment]
@manuel TVA-Insourcing as example: https://github.com/collectivemedia/tva-insource/blob/master/src/main/cycle/build.xml

**Comment by ezhulenev** [comment]
@ashf72 done great job for integrating Ant and Java Action, so it's not an issue anymore
