### ISSUE TITLE
incorrect documentation on  time value for celos UI

### ISSUE THREAD

**Issue by btrofimov** [collectivemedia/celos#649]
time parameter in celos UI accepts only stuff like  _time=_``` 2015-09-09T18:31:42-00 ```
However documentation says it just should conform to ISO 8601 which is much wider.
If I push just "ISO 8601" time like ``` time=2015-09-09T18:31:42 ```  then celos will show an error 

``` javax.servlet.ServletException: java.lang.IllegalArgumentException: Scheduled time must be in UTC, but isn't: 2015-09-09T18:31:42.000-04:00 ```

Expected: documentation should mention explicitly that UTC time zone is required.

**Comment by manuel** [comment]
Thanks, fixed
