### ISSUE TITLE
Weird Javascript parsing error on non-existing line

### ISSUE THREAD

**Issue by ezhulenev** [collectivemedia/celos#674]
When I try to create andTrigger with workflow that doesn't exists I get error from Javascript library, but the failing line (170) doesn't exists in workflow.js

Caused by: https://github.com/collectivemedia/audience-modeling-etl/blob/a242e3145d233e7096d43ee97af8c1d7328c0b57/src/main/cycle/workflow.js#L94

**Comment by ezhulenev** [comment]
It's caused by `null` passed into offset trigger

**Comment by manuel** [comment]
Figured this one out: #676 and #675
